In [9]:
from regpy.fts_pull import fts
from regpy.rw_pull import rw
import regpy.sc_pull
import regpy.desinv_pull

sc = regpy.sc_pull.pull()

def get_rw():
    r = rw(test = None, year = 2005, sc = sc)
    return r.master_pull()

def get_fts():
    all_f = fts(sc = sc, all_sector=True)
    s_f = fts(sc = sc)

    all_b = all_f.get_flow_bdown()
    all_b.rename({'total': 'all_total'}, inplace=True, axis=1)

    sf_b = s_f.get_flow_bdown()
    sf_b.rename({'total': 'sc_total'}, inplace=True, axis=1)

    mrgd = sf_b.merge(all_b[['sc.uid', 'all_total']], how='left', on='sc.uid')
    mrgd['all_total'] = mrgd['all_total'] - mrgd['sc_total']
    mrgd.columns = ['fts_' + v for v in mrgd.columns]
    
    return mrgd


rw = get_rw()
fts = get_fts()
div = regpy.desinv_pull.pull()

loaded 227 SC entries
pulling down from rw entry count of: 3021
trim data length: 1701
Pulling individual for hrefs to 0
Pulling individual for hrefs to 200
Pulling individual for hrefs to 400
Pulling individual for hrefs to 600
Pulling individual for hrefs to 800
Pulling individual for hrefs to 1000
Pulling individual for hrefs to 1200
Pulling individual for hrefs to 1400
Pulling individual for hrefs to 1600
pulled countries
num bad resps: 0

/Users/ewanog/Documents/work/code/venv/p3/lib/python3.6/site-packages/pandas/core/frame.py:6201: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=True'.

To retain the current behavior and silence the warning, pass sort=False

  sort=sort)

pulled countries
num bad resps: 0

In [61]:
# from regpy.fts_pull import fts

# def get_fts():
#     all_f = fts(sc = sc, all_sector=True)
#     s_f = fts(sc = sc)

#     all_b = all_f.get_flow_bdown()
#     all_b.rename({'total': 'all_total'}, inplace=True, axis=1)

#     sf_b = s_f.get_flow_bdown()
#     sf_b.rename({'total': 'sc_total'}, inplace=True, axis=1)

#     mrgd = sf_b.merge(all_b[['sc.uid', 'all_total']], how='left', on='sc.uid')
#     mrgd['all_total'] = mrgd['all_total'] - mrgd['sc_total']

#     return mrgd

# fts = get_fts()

pulled countries
num bad resps: 0

/Users/ewanog/Documents/work/code/venv/p3/lib/python3.6/site-packages/pandas/core/frame.py:6201: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=True'.

To retain the current behavior and silence the warning, pass sort=False

  sort=sort)

pulled countries
num bad resps: 0

/Users/ewanog/Documents/work/code/repos/humanitarian/shelter/sohss/regpy/fts_pull.py:97: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  v['sourceObjects']).values:

In [66]:
fts = fts.rename({'sc.uid' : 'fts.uid'}, axis = 1)

fts

plan  fts.uid  has_plan    no_plan   sc_total   all_total
0     AFG2008         0    5591549    5591549   545858739
1     AFG2009  25472179    3513009   28985188   607221589
2     AFG2010  31890043    3900869   35790912   541932989
3     AFG2011   8163742    9171957   17335699   597155660
4     AFG2012  11385904    1195950   12581854   451615156
5     AFG2013  32521337     149591   32670928   301588421
6     AFG2014  19520480     944681   20465161   502716700
7     AFG2015   5470535    1936544    7407079   494685402
8     AFG2016  14039028     408879   14447907   354633642
9     AFG2017  28094066    4127689   32221755   323034522
10    AFG2018   5470208    3019324    8489532   194119703
11    BEN2010   1638869    1423116    3061985    10019476
12    BFA2009    968253    1455723    2423976    78848327
13    BGD2007         0   13419063   13419063   289071744
14    BGD2009         0    4921148    4921148    32367563
15    BGD2012         0     610252     610252    34915291
16    BGD2013         0     241470     241470    33194734
17    BGD2014         0      19318      19318    40524221
18    BGD2015         0       6911       6911    41980125
19    BGD2016         0    1920338    1920338    35155381
20    BGD2017  39822025   15654006   55476031   102529311
21    BGD2018  21985593    2246442   24232035   176521981
22    CAF2007   1158174     589370    1747544    75228161
23    CAF2009    582324     127429     709753    93034616
24    CAF2010         0     700280     700280   100217033
25    CAF2012    200000          0     200000   116329545
26    CAF2013    316428     773410    1089838   149651638
27    CAF2014   7588191    1526477    9114668   249475348
28    CAF2015   5551409    1243868    6795277   317396003
29    CAF2016   1429001     874098    2303099   186621508
..        ...       ...        ...        ...         ...
180   TCD2008         0      78900      78900   349171326
181   TCD2009         0     551000     551000   423045239
182   TCD2011         0     408719     408719   358539371
183   TCD2013         0     799688     799688   357104190
184   TCD2014   1424954          0    1424954   307493776
185   TCD2015    401616          0     401616   312301040
186   TCD2016   1201281          0    1201281   331157323
187   TCD2017   1049000    4967940    6016940   342551549
188   TCD2018    490798      23238     514036   176569431
189   TJK2008   2290081    4732298    7022379    86439150
190   TON2018         0    3645028    3645028    10107122
191   UGA2006   1496344    2316002    3812346   244891920
192   UKR2014   4026652     723096    4749748    78813189
193   UKR2015  16030316    1720013   17750329   203090119
194   UKR2016   9931212    9042408   18973620   267259378
195   UKR2017   6132865   10703462   16836327   134719237
196   UKR2018   6598055     149068    6747123    65013939
197   VUT2015   2340841    1628189    3969030    39766531
198   VUT2017         0      24058      24058     1130173
199   YEM2008   1519593    1179262    2698855   234784418
200   YEM2009   6043353    6028722   12072075   172886267
201   YEM2010  14699871          0   14699871   157842630
202   YEM2011  12836153   41870589   54706742   202997161
203   YEM2012  20458584     183780   20642364   307033147
204   YEM2013  14542436    2570345   17112781   389836043
205   YEM2014   3942126     803248    4745374   463814986
206   YEM2015  45168677  136969680  182138357   450112708
207   YEM2016  25354518   33095354   58449872   557863847
208   YEM2017  22259013   43637707   65896720  1221351117
209   YEM2018  53959326    2008032   55967358   807828527

[210 rows x 5 columns]

In [76]:
fts.columns = ['fts_' + v for v in fts.columns]

fts

    fts_fts.uid  fts_has_plan  fts_no_plan  fts_sc_total  fts_all_total
0       AFG2008             0      5591549       5591549      545858739
1       AFG2009      25472179      3513009      28985188      607221589
2       AFG2010      31890043      3900869      35790912      541932989
3       AFG2011       8163742      9171957      17335699      597155660
4       AFG2012      11385904      1195950      12581854      451615156
5       AFG2013      32521337       149591      32670928      301588421
6       AFG2014      19520480       944681      20465161      502716700
7       AFG2015       5470535      1936544       7407079      494685402
8       AFG2016      14039028       408879      14447907      354633642
9       AFG2017      28094066      4127689      32221755      323034522
10      AFG2018       5470208      3019324       8489532      194119703
11      BEN2010       1638869      1423116       3061985       10019476
12      BFA2009        968253      1455723       2423976       78848327
13      BGD2007             0     13419063      13419063      289071744
14      BGD2009             0      4921148       4921148       32367563
15      BGD2012             0       610252        610252       34915291
16      BGD2013             0       241470        241470       33194734
17      BGD2014             0        19318         19318       40524221
18      BGD2015             0         6911          6911       41980125
19      BGD2016             0      1920338       1920338       35155381
20      BGD2017      39822025     15654006      55476031      102529311
21      BGD2018      21985593      2246442      24232035      176521981
22      CAF2007       1158174       589370       1747544       75228161
23      CAF2009        582324       127429        709753       93034616
24      CAF2010             0       700280        700280      100217033
25      CAF2012        200000            0        200000      116329545
26      CAF2013        316428       773410       1089838      149651638
27      CAF2014       7588191      1526477       9114668      249475348
28      CAF2015       5551409      1243868       6795277      317396003
29      CAF2016       1429001       874098       2303099      186621508
..          ...           ...          ...           ...            ...
180     TCD2008             0        78900         78900      349171326
181     TCD2009             0       551000        551000      423045239
182     TCD2011             0       408719        408719      358539371
183     TCD2013             0       799688        799688      357104190
184     TCD2014       1424954            0       1424954      307493776
185     TCD2015        401616            0        401616      312301040
186     TCD2016       1201281            0       1201281      331157323
187     TCD2017       1049000      4967940       6016940      342551549
188     TCD2018        490798        23238        514036      176569431
189     TJK2008       2290081      4732298       7022379       86439150
190     TON2018             0      3645028       3645028       10107122
191     UGA2006       1496344      2316002       3812346      244891920
192     UKR2014       4026652       723096       4749748       78813189
193     UKR2015      16030316      1720013      17750329      203090119
194     UKR2016       9931212      9042408      18973620      267259378
195     UKR2017       6132865     10703462      16836327      134719237
196     UKR2018       6598055       149068       6747123       65013939
197     VUT2015       2340841      1628189       3969030       39766531
198     VUT2017             0        24058         24058        1130173
199     YEM2008       1519593      1179262       2698855      234784418
200     YEM2009       6043353      6028722      12072075      172886267
201     YEM2010      14699871            0      14699871      157842630
202     YEM2011      12836153     41870589      54706742      202997161
203     YEM2012      20458584       183780      20642364      307033147
204     YEM2013      14542436      2570345      17112781      389836043
205     YEM2014       3942126       803248       4745374      463814986
206     YEM2015      45168677    136969680     182138357      450112708
207     YEM2016      25354518     33095354      58449872      557863847
208     YEM2017      22259013     43637707      65896720     1221351117
209     YEM2018      53959326      2008032      55967358      807828527

[210 rows x 5 columns]

In [82]:
div

,div_country_code,div_country,div_year,div_deaths,div_injured,div_missing,div_houses_destroyed,div_houses_damaged,div_relocated,div_evacuated,div_losses_$usd,div_uid
0,PAK,Pakistan,2005,45319,100789,1475,356908,180696,29199,1344,0.000000e+00,PAK2005
1,PAK,Pakistan,2006,9730,21534,851505,44488,59486,0,2315,0.000000e+00,PAK2006
2,PAK,Pakistan,2007,4411,27365,397,143441,44132,200,1982,0.000000e+00,PAK2007
3,PAK,Pakistan,2008,7695,25509,723,59099,38749,92,28000,0.000000e+00,PAK2008
4,PAK,Pakistan,2009,6911,60040,139,21114,25906,785,1214,0.000000e+00,PAK2009
5,PAK,Pakistan,2010,5105,19189,315,48235,72661,0,39745,0.000000e+00,PAK2010
6,PAK,Pakistan,2011,2561,10360,114,858749,272148,0,28000,0.000000e+00,PAK2011
7,PAK,Pakistan,2012,3224,26888,279,491576,906784,863,0,0.000000e+00,PAK2012
8,PAK,Pakistan,2013,3544,8412,403,73668,17586,215,6,0.000000e+00,PAK2013
9,PAK,Pakistan,2014,1443,4321,133,7816,6750,0,0,0.000000e+00,PAK2014
10,IDN,Indonesia,2005,2013,28795,35,0,0,0,322085,0.000000e+00,IDN2005
11,IDN,Indonesia,2006,7411,122631,488,0,0,0,2508263,0.000000e+00,IDN2006
12,IDN,Indonesia,2007,942,29155,361,0,0,0,1533295,0.000000e+00,IDN2007
13,IDN,Indonesia,2008,470,72800,154,0,0,0,610162,0.000000e+00,IDN2008
14,IDN,Indonesia,2009,1980,6067,658,208250,0,0,402168,0.000000e+00,IDN2009
15,IDN,Indonesia,2010,1772,36673,367,23045,3866,0,942755,0.000000e+00,IDN2010
16,IDN,Indonesia,2011,690,1097,262,15889,3412,0,232359,0.000000e+00,IDN2011
17,IDN,Indonesia,2012,399,1528,114,13615,8131,0,141598,0.000000e+00,IDN2012
18,IDN,Indonesia,2013,691,3613,128,17983,12590,0,510160,0.000000e+00,IDN2013
19,IDN,Indonesia,2014,751,2348,229,20140,6076,0,861120,0.000000e+00,IDN2014
20,IDN,Indonesia,2015,320,463,125,5254,3871,0,184254,0.000000e+00,IDN2015
21,IDN,Indonesia,2016,605,2824,157,9048,9979,0,438925,0.000000e+00,IDN2016
22,IDN,Indonesia,2017,392,1020,90,4495,3972,0,220493,0.000000e+00,IDN2017
23,IDN,Indonesia,2018,121,240,11,1572,3162,0,38642,0.000000e+00,IDN2018
24,LBN,Lebanon,2005,1,0,0,1,0,0,108,0.000000e+00,LBN2005
25,LBN,Lebanon,2006,5,1,0,0,0,0,0,0.000000e+00,LBN2006
26,LBN,Lebanon,2007,0,57,0,0,1,0,0,5.000000e+05,LBN2007
27,LBN,Lebanon,2008,4,457,0,1,1,0,0,0.000000e+00,LBN2008
28,LBN,Lebanon,2009,0,3,0,2,14,0,0,0.000000e+00,LBN2009
29,LBN,Lebanon,2010,0,0,0,0,0,0,0,0.000000e+00,LBN2010
...,...,...,...,...,...,...,...,...,...,...,...,...
223,SYR,Syrian Arab Republic,2005,24,47,0,3,144,0,15,0.000000e+00,SYR2005
224,SYR,Syrian Arab Republic,2006,69,92,0,171,113,20,75,0.000000e+00,SYR2006
225,SYR,Syrian Arab Republic,2007,157,286,0,1,38,0,0,0.000000e+00,SYR2007
226,SYR,Syrian Arab Republic,2008,248,534,0,8,86,25,0,0.000000e+00,SYR2008
227,SYR,Syrian Arab Republic,2009,52,98,0,1,17,0,26,0.000000e+00,SYR2009
228,ECU,Ecuador,2005,64,0,4,97,1810,0,480,7.400000e+05,ECU2005
229,ECU,Ecuador,2006,51,0,31,241,3060,80,4503,9.000000e+04,ECU2006
230,ECU,Ecuador,2007,30,127,6,529,1674,720,613,1.855000e+05,ECU2007
231,ECU,Ecuador,2008,160,326,21,461,14858,1404,5114,9.000000e+03,ECU2008
232,ECU,Ecuador,2009,58,331,11,282,1750,37,681,6.000000e+03,ECU2009
233,ECU,Ecuador,2010,133,249,11,147,414,0,2655,3.000000e+01,ECU2010
234,ECU,Ecuador,2011,435,1291,13,613,4999,0,128738,0.000000e+00,ECU2011
235,ECU,Ecuador,2012,685,2414,0,722,20206,0,9662,0.000000e+00,ECU2012
236,ECU,Ecuador,2013,589,3032,58,636,5562,0,1588,0.000000e+00,ECU2013
237,ECU,Ecuador,2014,513,2828,58,686,4113,7,2199,0.000000e+00,ECU2014
238,ECU,Ecuador,2015,486,2283,66,684,5788,7,1375,6.893950e+05,ECU2015
239,ECU,Ecuador,2016,937,3868,72,9095,20349,0,5080,0.000000e+00,ECU2016
240,ECU,Ecuador,2017,255,867,13,604,15543,3,2280,0.000000e+00,ECU2017
241,ECU,Ecuador,2018,10,45,2,75,246,0,97,0.000000e+00,ECU2018
242,MDG,Madagascar,2005,55,0,260,0,7734,2841,0,2.302185e+07,MDG2005
243,MDG,Madagascar,2006,13,2,6,0,384,558,0,1.403304e+07,MDG2006
244,MDG,Madagascar,2007,151,128,30,58281,0,39400,0,1.126926e+08,MDG2007
245,MDG,Madagascar,2008,137,751,176,137144,0,111971,0,6.448267e+07,MDG2008
246,MDG,Madagascar,2009,77,12,0,1235,0,0,0,3.599495e+06,MDG2009
247,MDG,Madagascar,2010,144,182,34,26957,3,74088,0,0.000000e+00,MDG2010
248,MDG,Madagascar,2011,117,84,7,8565,16545,24239,38,2.031520e+07,MDG2011
249,MDG,Madagascar,2012,169,314,3,45830,35994,0,0,3.942248e+07,MDG2012
250,MDG,Madagascar,2013,97,98,18,6634,36884,36310,0,0.000000e+00,MDG2013
251,MDG,Madagascar,2014,118,34,10,699,174,0,0,0.000000e+00,MDG2014
252,MDG,Madagascar,2015,215,68,9,6971,826,79010,0,0.000000e+00,MDG2015

In [84]:
sc = regpy.sc_pull.pull()

#merge rw
rw_cnt = pd.DataFrame(rw['rw.uid'].value_counts()).reset_index()
rw_cnt.columns = ['rw.uid', 'rw.cnt']
c

#merge fts
sc = sc.merge(fts, left_on = 'sc.uid', right_on = 'fts_fts.uid', how = 'left')

#merge div
sc = sc.merge(div, left_on = 'sc.uid', right_on = 'div_uid', how = 'left')

#drop cols
sc.drop('rw.uid', axis = 1)
sc.drop('fts_fts.uid', axis = 1)
sc.drop('div_uid', axis = 1)

loaded 227 SC entries

178

In [94]:
fts.to_csv('fts.csv')